### PR TITLE
Add from_local_environ

### PR DESCRIPTION
**Pull request by gongy**

### CODE REVIEW

**Review by erikbern — APPROVED** [review]
looks good to me! plz add test though

**Comment by gongy** [comment]
Yep, will test and polish this draft and re-request.

**Comment by aksh-at** [comment]
Btw this missed a changelog entry :(

**Comment by thundergolfer** [comment]
Oh damn, that's because the PR description predated the changelog and I didn't remember 😞

**Comment by mwaskom** [comment]
btw if you feel it's important you can always manually update `CHANGELOG.md`.

**Pull request merged**
