### PR TITLE
Use __future__.annotations part 2: remove more of the typing.List, typing.Dict usages

### PR DESCRIPTION
**Pull request by thundergolfer**
Follow-up to https://github.com/modal-labs/modal-client/pull/78.

### CODE REVIEW

**Comment by thundergolfer** [comment]
Argh, I think I've hit https://github.com/pydantic/pydantic/issues/2678

**Review by erikbern — APPROVED** [review]
nice!

**Comment by thundergolfer** [comment]
@erikbern it's not working unfortunately. See https://github.com/modal-labs/modal-client/pull/83#issuecomment-1322739791

**Comment by thundergolfer** [comment]
Will close this until I work out a way to 100% replace `from typing.List` with `list` without breaking `typer`.

**Pull request closed without merging**
