### PR TITLE
Deprecate modal.Proxy

### PR DESCRIPTION
**Pull request by ekzhang**
I think we should also add a page about Proxy IPs to the docs, so it can be searchable!

### CODE REVIEW

**Comment by mwaskom** [comment]
My understanding of @luiscape's current plan was that we would be migrating proxies to the new system and continue using the `modal.Proxy` name. Could be wrong about where we landed there, though.

**Comment by ekzhang** [comment]
> My understanding of @luiscape's current plan was that we would be migrating proxies to the new system and continue using the `modal.Proxy` name. Could be wrong about where we landed there, though.

We can continue using the `modal.Proxy` name but that will probably require a complete rewrite? We're currently moving people onto `_experimental_proxy_ip` for the time being.

**Comment by mwaskom** [comment]
> That will probably require a complete rewrite of this class, since it's built for the deprecated Proxy object at the moment?

This is what I wasn't sure about — it doesn't look like the object class in the client actually does anything relevant to the proxy mechanism?

**Comment by ekzhang** [comment]
Yeah, it's just the code in `_proxy_tunnel.py` right now. And the `apt_install("autossh")` hack. I think we could maybe deprecate this object, remove it, then reintroduce it in a future version so people don't get confused by the docs page for the old object?

image

**Comment by ekzhang** [comment]
@luiscape I indexed the "Proxy IPs" guide page you wrote in https://github.com/modal-labs/modal/pull/16743 so this PR will remove the docs for the deprecated modal.Proxy object

**Comment by erikbern** [comment]
My understanding is also that we'll keep the `Proxy` object in the client, but we'll swap out the code underneath.

**Pull request closed without merging**
