### PR TITLE
Update image.py

### PR DESCRIPTION
**Pull request by NicholasKao1029**
expose GPU for `image.extend` function

## Describe your changes

- expose the `gpu` parameter for `image.extend` similar to `image.pip_install`

## Backward/forward compatibility checks

Check these boxes or delete any item (or this section) if not relevant for this PR.

- [x] Client+Server: this change is compatible with old servers
- [x] Client forward compatibility: this change ensures client can accept data intended for later versions of itself

## Changelog

Let's a user enable a `gpu` when extending

### CODE REVIEW

**Comment by mwaskom** [comment]
Hey @NicholasKao1029 thanks for the PR!

Layers defined through `Image.extend` already can be run with a GPU, ala the following example:

```python
import modal

image = (
    modal.Image.from_registry("nvcr.io/nvidia/pytorch:22.12-py3")
    .extend(dockerfile_commands=["FROM base", "RUN nvidia-smi"], gpu_config=modal.gpu.parse_gpu_config("T4"))
)
stub = modal.Stub(image=image)

@stub.function()
def f():
    pass
```

Unlike most of the `Image` convenience method, `gpu_config` is narrowly typed as a `modal_proto.api_pb2.GPUConfig` object. But `Image.extend` is a low-level command so that makes sense.

I'm curious if there's a specific usecase that's required you to drop down to using `extend` directly. Is there something we could support better with a convenience method?

**Comment by NicholasKao1029** [comment]
@mwaskom Thanks this makes sense. No we use `extend` because for a portion of our install commands we use docker definitions already. Appreciate the explanation!

**Comment by mwaskom** [comment]
Would [`Image.dockerfile_commands'](https://modal.com/docs/reference/modal.Image#dockerfile_commands) work for you here?

```
def run_commands(
    self,
    *commands: Union[str, List[str]],
    secrets: Sequence[_Secret] = [],
    gpu: GPU_T = None,
    force_build: bool = False,
) -> "_Image":
"""Extend an image with arbitrary Dockerfile-like commands."""
```

We're discussing making `Image.extend` private as it doesn't really have a user-friendly public interface and we can't think of any usecases for running it directly that aren't currently satisfied by the higher-level `Image` methods.

**Comment by NicholasKao1029** [comment]
I think this could work and better!

**Pull request closed without merging**
