### PR TITLE
Remove ddtrace usage from client

### PR DESCRIPTION
**Pull request by ekzhang**
Part of an effort to minimize client library dependencies

### CODE REVIEW

**Comment by danielnorberg** [comment]
Isn’t ddtrace already an optional dependency?

**Comment by ekzhang** [comment]
It's included in client/modal/requirements.txt -- this is part of an effort to minimize that file

**Comment by ekzhang** [comment]
@prbot approve

**Comment by ekzhang** [comment]
We can't remove it from the requirements.txt file without breaking image builds. This is a long-term project.

**Comment by ekzhang** [comment]
https://www.notion.so/modal-com/Improving-modal-without-problematic-user-image-rebuilds-ecb1595337ad4797bcf11c5fdd9dccdc

**Pull request merged**
