### PR TITLE
Disallow getting the app from the stub

### PR DESCRIPTION
**Pull request by erikbern**
This turns a warning into an error, which lets me remove the `Stub._local_app` member next.

EDIT: also ended up removing the `spawn_sandbox` method from the `App` class since it's near pointless with `stub.app` (you _could_ call it from the global `container_app`, but I doubt it's common)

EDIT 2: passes all integration tests

### CODE REVIEW

**Review by aksh-at — APPROVED** [review]
Does this warrant a minor version bump?

**Comment by erikbern** [comment]
> Does this warrant a minor version bump?

Yeah why not – there's been a lot of deprecation changes in the last few weeks and it might be good to keep track of old client versions. I have a lot more deprecation changes coming up, but most of them just introduce warnings, which is probably less of a reason for a version bump. I think warning -> error is a bigger reason for bumps

**Comment by erikbern** [comment]
Thanks @aksh-at !

**Comment by aksh-at** [comment]
> I think warning -> error is a bigger reason for bumps

Yeah exactly, so if someone pins to ~=0.53.xyz for example they won't get hit with the deprecation errors automatically.

**Pull request merged**
