### PR TITLE
Handle stderr in CLI tests

### PR DESCRIPTION
**Pull request by erikbern**
I was hoping this would output the async traceback stuff, but I believe click doesn't run things in a subprocess so it doesn't properly capture the shutdown behavior. But this PR probably has some value for unrelated issues so I'm putting it up here.

### CODE REVIEW

**Comment by freider** [comment]
Oh I think I might have a branch locally that actually tests in a real sub process. Let me check!

**Comment by freider** [comment]
I can't find it but I'm like 90% sure I wrote tests for that when I did the synchronicity patch that ensures to propagate the cancellations to the event loop... :thinking: Might have accidentally nuked it from my working tree :shrug:

**Review by freider — APPROVED** [review]

**Comment by erikbern** [comment]
There's some stuff here that uses a subprocess: https://github.com/modal-labs/modal-client/blob/main/client_test/e2e_test.py

Will add something that runs `modal run`

**Comment by erikbern** [comment]
Actually, I'm stupid. The error we're looking for is printed inside the containers, not by the client.

**Pull request merged**
