### PR TITLE
Ship i6pn networking for containers

### PR DESCRIPTION
**Pull request by ekzhang**
This enables i6pn networking for containers. You can define a function with:

```python
import socket
import modal

app = modal.App()

@app.function(i6pn=True)
def func():
    worker_ip6 = socket.getaddrinfo("i6pn.modal.local", None, socket.AF_INET6)[0][4][0]
    print(worker_ip6)
```

And it will have an IPv6 address that can be used to communicate with other containers, _within the same cloud and region_.

Grouped functions need quite a bit more work before they can be made stable, including scheduler work, I'm just shipping i6pn for now so we can write some demos and docs.

### CODE REVIEW

**Comment by ekzhang** [comment]
@mwaskom I'm pretty agnostic about the name of the parameter being `i6pn` or `i6pn_enabled` or anything else, let me know if you would like it to be changed :)

**Comment by mwaskom** [comment]
> I'm pretty agnostic about the name of the parameter being i6pn or i6pn_enabled or enable_i6pn or anything else

I don't think I have a strong preference there (I think "enable" is probably subsumed by the boolean type) but my bigger concern is whether "i6pn" will mean anything to users. Doesn't seem like a commonly used term based on Google?

**Comment by ekzhang** [comment]
> Doesn't seem like a commonly used term based on Google?

Yeah, it will be explained in our docs, it's the name of our feature. Modal's implementation of IPv6 Private Networking via some ebpf overlay stuff.

It's also exposed in the `i6pn.modal.local` DNS. Some other options:

- Expand the parameter name to `ipv6_private_networking=True`
  - I don't love this because it gives the feature a new "official name" whereas we could just call it i6pn always
- Always enable it
  - This is an option since it doesn't slow down containers that don't use it or anything, though I'd want to maybe test it a bit more before we enable it globally

**Comment by ekzhang** [comment]
@prbot approve

Merging to unblock examples. I can change the function parameter name later though.

**Comment by arpagon** [comment]
Wow, thanks for this! It means a lot to see IPv6 support starting in Modal.

I don’t want to sound demanding, but I’m looking forward to seeing full IPv6 support soon. Any news or plans on that front?

**Comment by ekzhang** [comment]
Could you clarify what your intended use case is? IPv6 is just a protocol and can be used in a lot of ways.

Feel free to send us a message in #community-feature-requests on https://modal.com/slack

**Pull request merged**
