### PR TITLE
rename 'Function env' to 'Function spec'

### PR DESCRIPTION
**Pull request by thundergolfer**
## Describe your changes

image

* Calling this an "environment" clashes with our Environment domain term. 
* We also had this dataclass in the docs 

## Backward/forward compatibility checks

- [x] Client+Server: this change is compatible with old servers
- [x] Client forward compatibility: this change ensures client can accept data intended for later versions of itself

### CODE REVIEW

**Comment by mwaskom** [comment]
Nice, makes sense.

Why do we have public docs for this btw? Is this something users would ever interact with directly?

**Comment by mwaskom** [comment]
Oh I see you're also making it private, so we won't going forward?

**Comment by thundergolfer** [comment]
Yep, it'll be hidden

**Review by mwaskom — APPROVED** [review]

**Comment by mwaskom** [comment]
Makes sense. Sort of confusing how most of our objects look private on declaration but then become public when they get synchronicity wrapped. Different issue though :)

**Pull request merged**
