### PR TITLE
Expose list of fallback GPU types

### PR DESCRIPTION
**Pull request by irfansharif**

### CODE REVIEW

**Comment by irfansharif** [comment]
image

**Comment by irfansharif** [comment]
@prbot approve

**Comment by irfansharif** [comment]
Will address comments in follow up - sure there are things to improve. Checking it in to start running synmon tests.

**Review by thundergolfer — COMMENTED** [review]
LGTM, and I've added review comments by just creating a follow-on PR: https://github.com/modal-labs/modal-client/pull/2273

**Pull request merged**
