### PR TITLE
Implement `App.lookup`

### PR DESCRIPTION
**Pull request by aksh-at**
## Changelog

App handles can now be looked up by name with `modal.App.lookup(name)`. This can be useful for associating sandboxes with apps:

```python
app = modal.App.lookup("my-app", create_if_missing=True)
modal.Sandbox.create("echo", "hi", app=app)
```

### CODE REVIEW

**Comment by mwaskom** [comment]
What happens if you do the following?


```python
app = modal.App.lookup("my-app")

@app.function()
def new_function():
    pass

modal.runner.deploy_app(app)
```

**Comment by aksh-at** [comment]
> What happens if you do the following?

Hah, it actually works. As discussed offline we need to disallow some operations on hydrated apps in general — e.g. right now it also works if you redeployed an app from within a container while it was running, but that maybe shouldn't be possible?

**Comment by aksh-at** [comment]
@prbot approve

**Comment by erikbern** [comment]
👍

**Pull request merged**
