### PR TITLE
Auto-snapshot __enter__ functions

### PR DESCRIPTION
**Pull request by aksh-at**
See [doc](https://www.notion.so/modal-com/Auto-__enter__-snapshots-50e8d9cd12c54031b10aa8b864b09d0c?pvs=4)

### CODE REVIEW

**Comment by erikbern** [comment]
Wow this is so simple that we should have done this a long time ago in hindsight :)

super cool!

**Comment by aksh-at** [comment]
Making it opt-in for now (have to put `auto_snapshot_enabled=True` in the `cls` decorator). Will enable globally after some more testing.

**Comment by aksh-at** [comment]
@prbot approve

**Comment by aksh-at** [comment]
Works great with our stable diffusion example

image

**Comment by erikbern** [comment]
Nice! Let's rewrite our examples to leverage this?

**Pull request merged**
