### PR TITLE
Load function sub-entities in parallel

### PR DESCRIPTION
**Pull request by freider**
Load all mounts, secrets, images and shared_volumes for a function in parallel

### CODE REVIEW

**Comment by freider** [comment]
> This is a great speedup! My main concern is let's make sure it works if there are multiple objects depending on the same object – something like this has a risk of introducing race conditions.

I think this is resolved by the new "shared futures" logic in the Resolver (see the test_multi_resolve_concurrent_loads_once test I added as well). Basically "get or create" a new asyncio task for each load on the same object local uuid, so all dependents resolve by the same future and only load once. Not sure if I missed thinking about some aspect of it though 🤔

**Comment by erikbern** [comment]
alright cool, if you feel confident then let's ship it! 🚢

**Comment by freider** [comment]
> alright cool, if you feel confident then let's ship it! 🚢

Can haz ✅ ?

**Review by erikbern — APPROVED** [review]

**Comment by erikbern** [comment]
@freider what's the status of this one?

**Comment by freider** [comment]
There was some unrelated test-flake and then pip publishing issues that stalled the merge (wanted to be available to monitor after the merge in case something unexpected started breaking for new users).
Merging now :)

**Pull request merged**
