### PR TITLE
bump to 0.70 and receive AppLayout from worker

### PR DESCRIPTION
**Pull request by erikbern**
The server will provide the app layout for clients 0.70+

### CODE REVIEW

**Comment by erikbern** [comment]
will figure out what's up with sandboxes separately

**Comment by erikbern** [comment]
oops, accidentally closed the wrong PR

**Comment by erikbern** [comment]
@prbot approve

**Comment by erikbern** [comment]
tried running this in prod and it works beautifully. it receives an app layout from the worker and does not need to hit `AppGetLayout`. I'll keep the "dead code" for a short bit though

**Review by mwaskom — COMMENTED** [review]
✅

**Pull request merged**
