### PR TITLE
WIP: Modal method calling a local function

### PR DESCRIPTION
**Pull request by erikbern**
Currently just reproduces a problem reported by a user. Will work on a fix next.

### CODE REVIEW

**Comment by danielnorberg** [comment]
Afaiu my repro was not parameterized, not sure if that matters.

**Comment by erikbern** [comment]
Yeah you're right, it has to do with the class, not whether it uses parameters. Let me rename the PR.

**Comment by erikbern** [comment]
I think the fix should work. That being said, I'm not super happy with this fix – I think it would be better if a function "knows" that it's a method and if you call `.local()` when an object isn't present, it should fail. Will see if I can fix.

**Comment by erikbern** [comment]
I suspect there are some weird cases that might still cause issues, e.g. if the `@cls` decorator isn't in global scope but applied independently. But tbh this feels like a pretty fringe use case. We can deal with it later.

**Pull request merged**
