### PR TITLE
fix: typo `object` to `obj` in isfunction check

### PR DESCRIPTION
**Pull request by deepankarm**
## Describe your changes

Minor fix in `isfunction` check

### CODE REVIEW

**Comment by erikbern** [comment]
Awesome!

Did this lead to a bug? Asking since it would be great to add a unit test as well

**Comment by deepankarm** [comment]
> Did this lead to a bug?

No, I was just exploring the code. 

> it would be great to add a unit test

I added one. Please check if it's good enough.

**Comment by mwaskom** [comment]
I don't understand why this isn't running the CI-CD workflow 🤔

**Review by mwaskom — APPROVED** [review]
LGTM

**Pull request merged**
