### PR TITLE
Add AWS_REGION in code sample for S3 bucket

### PR DESCRIPTION
**Pull request by yirenlu92**
- Add AWS_REGION in code sample for S3 bucket

### CODE REVIEW

**Comment by mwaskom** [comment]
What effect does this have?

**Comment by thundergolfer** [comment]
Agree with @mwaskom's question. What's the region of (the bucket) and how do you find the region for the bucket. The other two key-values are more self-explanatory, but arguably could also get documented.

**Comment by luiscape** [comment]
Mountpoint supports `AWS_REGION` [as a parameter](https://github.com/awslabs/mountpoint-s3/blob/bd9b1af33128f235b26bbeaee5c586d22de748e2/doc/CONFIGURATION.md#region-detection). The main use-case seems to be resolving issues that may happen with "cross-region mount with a directory bucket", among other things.

Seems fair to add it as an optional env var.

**Comment by mwaskom** [comment]
This was just a genuine question on my end; it’s not clear from the example what this is supposed to accomplish. (Are you setting the region you are connecting from? The region you want to mount in? Etc.)

**Comment by mwaskom** [comment]
Thanks for adding the comments, makes a lot more sense.

So that they remain readable, can we move the comments to a line above the parameter and wrap them at a reasonable character width?

**Review by mwaskom — APPROVED** [review]
Thanks for bearing with me :)

**Pull request merged**
